# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 映射资源地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.page.demo.domain